### ISSUE TITLE
How filter belongsToMany ?

### ISSUE THREAD

**Issue by piterssson** [ziffmedia/nova-select-plus#10]
I would like to add clausere "where" from select belongsToMany. Now when added join and where show all fields....

**Comment by ralphschindler** [comment]
Sorry, I don’t think I understand, perhaps you can explain your request with a use case?

**Comment by piterssson** [comment]
> Sorry, I don’t think I understand, perhaps you can explain your request with a use case?

I would like to add where to query in SelectPlus field

**Comment by ralphschindler** [comment]
So, to understand better, you want a way that you can filter out specific relational models that can be attached/synced to a particular resource/model specifically when it is *not searchable*? (You are able to do any kind of `->where()` or other query methods if you are making the select `ajaxSearchable`, as in the docs.)

like:

```php
SelectPlus::make('States Lived In', 'statesLivedIn')
    ->optionsQuery(function ($query) {
        $query->where(..');
    });
```

does that sound like what you're asking for?

**Comment by piterssson** [comment]
> So, to understand better, you want a way that you can filter out specific relational models that can be attached/synced to a particular resource/model specifically when it is _not searchable_? (You are able to do any kind of `->where()` or other query methods if you are making the select `ajaxSearchable`, as in the docs.)
> 
> like:
> 
> ```
> SelectPlus::make('States Lived In', 'statesLivedIn')
>     ->optionsQuery(function ($query) {
>         $query->where(..');
>     });
> ```
> 
> does that sound like what you're asking for?

great :) thanks

**Comment by ralphschindler** [comment]
Added in v1.0.7
