### ISSUE TITLE
Feature Request: option to customize the result text

### ISSUE THREAD

**Issue by gavinhewitt** [ziffmedia/nova-select-plus#16]
Hi, 

I have terms that are written the same, but different id's and in different categories and I would like to be able to distinguish between them. It would be very helpful if you could add something to the result so you can see which one is which.

**Comment by ralphschindler** [comment]
I do have an upcoming feature where you can customize the label with html... still working out some of the details, but basically looks like this:

https://github.com/ziffmedia/nova-select-plus/blob/demo-app/demo/app/Nova/Person.php#L79

**Comment by ralphschindler** [comment]
Please see the v1.0.8 release with the `label` using a closure:

https://github.com/ziffmedia/nova-select-plus/blob/master/readme.md#-labelstringclosure-attribute-pick-a-different-attribute-to-use-as-the-label
