### ISSUE TITLE
Help text is not appearing

### ISSUE THREAD

**Issue by scottgrayson** [ziffmedia/nova-select-plus#24]
https://nova.laravel.com/docs/3.0/resources/fields.html#field-help-text

Trying the nova method of adding help text and it does not appear

**Comment by ralphschindler** [comment]
Hi!

I am unable to reproduce this. I have the latest version checked out, and in the demo app:
https://github.com/ziffmedia/nova-select-plus/blob/master/demo/app/Nova/Person.php#L61

And it shows in my UI:
![2020-10-08-09-19-27](https://user-images.githubusercontent.com/76674/95471283-64004780-0947-11eb-810c-54d36d0350cd.png)

**Comment by ralphschindler** [comment]
If you have more information on how to reproduce, I am completely willing to re-open. Let me know, thanks!
