### ISSUE TITLE
Enhancement - Pass the current resource ID to the optionsQuery callback

### ISSUE THREAD

**Issue by archangel2080** [ziffmedia/nova-select-plus#30]
It would be great if the `optionsQuery` callback could get the current resource ID like the `ajaxSearchable` callback.

**Comment by ralphschindler** [comment]
Fixed in https://github.com/ziffmedia/nova-select-plus/releases/tag/v1.0.10

**Comment by Paulsky** [comment]
Do you have any documentation available for this? I would like to use `viaResourceId` in the `optionsQuery` for filtering the relations
