### ISSUE TITLE
Help text is not showing up on the form

### ISSUE THREAD

**Issue by archangel2080** [ziffmedia/nova-select-plus#31]
To reproduce:
Make a SelectPlus on a Resource and add help text then load the create or update form.

Example:
```
class Bar extends Resource
{
    public functions fields ($request)
    {
          return [
              SelectPlus::make('Foos', 'foos', Foo::class)
                  ->help('Select all related foos');
          ];
     }
}
```
I believe this is fixable by adding `:show-help-text="showHelpText"` to the `<default-field …>` tag [here](https://github.com/ziffmedia/nova-select-plus/blob/master/resources/js/components/FormField.vue#L2)

**Comment by ralphschindler** [comment]
Fixed in release https://github.com/ziffmedia/nova-select-plus/releases/tag/v1.0.10
