### ISSUE TITLE
Relationship Resource is not a valid class 

### ISSUE THREAD

**Issue by OthmanAlseagh** [ziffmedia/nova-select-plus#32]
Error  Relationship Resource is not a valid class 

when i use 

SelectPlus::make('Employees', 'employees',  \App\Models\Employee::onlyMines()->get())

**Comment by OthmanAlseagh** [comment]
class Services {
 public function employees(): BelongsToMany
    {
        return $this->belongsToMany(Employee::class);
    }
}

this is my class

**Comment by ralphschindler** [comment]
Hi!
See https://github.com/ziffmedia/nova-select-plus/blob/master/demo/app/Nova/Person.php#L54

The 3rd parameter to the `make()` method must be the class of the Resource (not the model class) you are trying to map to.
