### ISSUE TITLE
Doesn't show option titles in list

### ISSUE THREAD

**Issue by krisis32** [ziffmedia/nova-select-plus#37]
Options titles are not shown in select list and on new selected item (last item in image).
If I save, then the name of item is shown.
<img width="740" alt="Screenshot 2021-06-21 at 12 10 14 PM" src="https://user-images.githubusercontent.com/1643150/122737962-387d7d00-d28a-11eb-8bc6-7285dac54ac8.png">

**Comment by ralphschindler** [comment]
What does your component setup look like inside the resource? and what does the relationship definition (inside the model) look like?

**Comment by HeadStudios** [comment]
Same here - https://share.getcloudapp.com/12uRDRdK - CSS makes it unusable

**Comment by ralphschindler** [comment]
Please try [v2.0.2](https://github.com/ziffmedia/nova-select-plus/releases/tag/v2.0.2) for nova 4, thanks!
