### ISSUE TITLE
Feature request | Categorizable Select

### ISSUE THREAD

**Issue by ChristianPavilonis** [ziffmedia/nova-select-plus#39]
It would be nice to categorize items based on a column on the selectable items.

Example:
```
SelectPlus::make('Related Products')->categorizeBy('department');
```
This would output a categorized list of products based on department.

**Comment by ralphschindler** [comment]
What do you mean by categorized? Sorted or grouped and after grouped, indented?

**Comment by ChristianPavilonis** [comment]
@ralphschindler Yes grouped and indented. In my example it would output:

- Department A
  - Product A
  - Product B
- Department B
  - Product C
  - Product D
