### ISSUE TITLE
Please add support for Nova 4

### ISSUE THREAD

**Issue by newtec-foggia** [ziffmedia/nova-select-plus#44]
Hi,

Please add support for Nova 4.
Regards

**Comment by meyer59** [comment]
Waiting for the update too

**Comment by ralphschindler** [comment]
This is proving to be more substantial than originally expecting due to changes in Nova (specifically around vuedraggable and the upgrade to vue 3). I am continuing to work on this, will give another update this week.

**Comment by jjjrmy** [comment]
can't wait :)

**Comment by eugenevdm** [comment]
Yep also quite keen. The VueJS stuff is way over my head so unfortunately I can't contribute to a pull request. But of all the pacakges that I miss, this one seems unique and not replaceable.

**Comment by ralphschindler** [comment]
Much progress made, I may be able to finalize in the next day or so #47

**Comment by ralphschindler** [comment]
Please try v2.0.0 and let me know if you run into any issues!
