### ISSUE TITLE
Dropdown options hidden by `overflow-hidden`

### ISSUE THREAD

**Issue by nilsenpaul** [ziffmedia/nova-select-plus#65]
When the `SelectPlus` Nova field is used near the end of a Nova panel, most dropdown options are hidden by the `overflow-hidden` on the container. Is this something you can change, or do you know a work-around?

<img width="848" alt="overflow-hidden" src="https://github.com/ziffmedia/nova-select-plus/assets/6794819/725fc442-ea7d-4d85-80ec-4b5c95861353">

**Comment by bigperson** [comment]
i have some problem

**Comment by ralphschindler** [comment]
Please try `v2.0.5` - this is a nova problem, but I put a bandaid in place until it is fixed upstream.
https://github.com/laravel/nova-issues/issues/6096
